arch:
- arm64
- s390x
- ppc64le

dist: xenial
language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6" # current default Python on Travis CI
- "3.7"
- "3.8"
- "3.8-dev" # 3.8 development branch
- "nightly" # nightly build

install: skip
script:
- python -V
#- python ./src/hello.py
matrix:
  include:
    - name: xenial
      name: xenial
    - dist: bionic
      name: bionic
